### ISSUE TITLE
Disabling the date range option

### ISSUE THREAD

**Issue by mikwee** [daveMcelf/simple_vertical_calendar#2]
I'd like to be able to disable the date range option, since it does not fit the project I'm working on. I'd appreciate your help.

**Comment by daveMcelf** [comment]
@mikwee I have made the update to the packages. the `1.1.0` is now support different calendar option now, including `RANGE_SELECTION`, `SINGLE`. 
you can make the specify it like this:
```
SimpleVerticalCalendar(
        numOfMonth: 6,
        calendarOption: CalendarOptions.SINGLE,
        onDateTap: (start, end) {
              // `start` and `end` has the same value for SINGLE option
        },
),
```
